name: runnning jmeter tests on Github actions

on:
  pull_request:
    branches:
      - main
  push: 
    branches:
      - main

jobs: 
  buid: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./wm_platform_sales_and_labor.jmx
          args: ""
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results.jtl
          if-no-files-found: error
      # Generate HTML report from the JTL results
      - name: Generate HTML Report
        run: |
          docker run --rm -v ${{ github.workspace }}:/test justb4/jmeter:latest \
          -g /test/result.jtl -o /test/report
      # Upload the HTML report as an artifact
      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: report
      - name: Send Report to Teams
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{
                "title": "JMeter Test Report",
                "text": "Performance test completed. Download the HTML report from the link below:",
                "sections": [{
                  "activityTitle": "JMeter Report",
                  "activitySubtitle": "Click [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts) to download the report."
                }]
              }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}