name: runnning jmeter tests on Github actions

on: 
  push:
  branches:
    main
  pull_request: 
    branches:
      main

jobs: 
  buid: 
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: JMeter Test
      uses: QAInsights/PerfAction@v5.6.2
      with:
        test-plan-path: ./wm_platform_sales_and_labor.jmx
        args: ""
    - name: Upload Results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results
        path: result.jtl
        if-no-files-found: error